### ISSUE TITLE
Could you add this bulb?

### ISSUE THREAD

**Issue by igiotis** [easyhomesrc/Homey_Issues#1]
Hi, is it possible to add support for this filament bulb off Aliexpress ? Supposed to be color changing too.

Man. ID. ZB/GMY-CCT
Product ID: CCT Light
Device ID: 268
Profile ID: 260

**Comment by easyhomesrc** [comment]
@igiotis 
Hi, I've added the device you provided to the Homey App, and it's waiting for review. Of course, you can also use the beta version for testing.

https://homey.app/en-us/app/com.easyhome.mw.zigbee/EasyHome/test/

**Comment by easyhomesrc** [comment]
@igiotis 
The device name in the Homey App is Light CCT (ZigBee ZHA)

**Comment by igiotis** [comment]
Sweet! Tested and works great. Thanks!!
