### ISSUE TITLE
Osram Ledvance GU5.3

### ISSUE THREAD

**Issue by vince983** [easyhomesrc/Homey_Issues#13]
HI!,
Can you add support for the OSRAM LEDavance SPOT GU5.3 TUNABLE WHITE?

manufacturerName:
OSRAM

productId:
MR16 TW OSRAM

DeviceID:
544

ProfileID:
49246

Tnx!

**Comment by maginawin** [comment]
Hi, @vince983 

I have added support for the device, you can test in advance, enable this App then go to [Devices > Add a device > Homey > Zigbee > Install]:
https://homey.app/en-us/app/com.easyhome.mw.zigbee/EasyHome/test/

App is now waiting for certification.

**Comment by vince983** [comment]
Hi,
now it works perfectly. 
Tnx!!!


Inviato da iPhone
