### ISSUE TITLE
FeiBit wall dimmer 

### ISSUE THREAD

**Issue by MitchNL** [easyhomesrc/Homey_Issues#14]
Hello. I tried adding two wall dimmers to my homey. Unfortunately Homey said: Zigbee Identified as an unknown device

Manufacturer ID: FeiBit
Product ID: FNB56-ZBW01LX1.2
Device ID: 256
Profile ID: 49246

I would be very happy if you could help me out. 

Kind regards,

Mitch

**Comment by easyhomesrc** [comment]
Hi, @MitchNL 

I have added support for the device, you can test in advance:
https://homey.app/en-us/app/com.easyhome.mw.zigbee/EasyHome/test/

App has been published and is awaiting review.

Regards

**Comment by MitchNL** [comment]
Hii,

I have installed it and it all works fine! Thank you very much for your help and your fast response!! I am very happy about the it.

Regards,

Mitch
