### ISSUE TITLE
Cenika Stove Guard

### ISSUE THREAD

**Issue by Allram** [easyhomesrc/Homey_Issues#18]
Hello,

We at Cenika is developing a new Stove Guard with Zigbee, we don't plan to support all of the smart home gateways ourselves, but do you think you can add the support for it in your app? I have a few devices for test and it will probably be released in the fall for the public.

I have all the Zigbee registry if you want it. We have made the device work like a "Philips Hue Outlet" with Power (Watt) / kWh and the status of the relay in the Stove Guard (On/Off). If you want i can send you the necessary registry's.

Manufacturer ID: Cenika
Product ID: Power Control Unit
Device ID: 81
Profile ID: 260

**Comment by easyhomesrc** [comment]
Hi, @Allram 

The Homey SDK will be updated in the next month, I will update the App after the Homey updated. You can send me the ZigBee registry before then.

**Comment by easyhomesrc** [comment]
@Allram 

I am very sorry, Homey requires that we can no longer add non-own brand products to the EasyHome App
