### ISSUE TITLE
Zigbee Wireless Dimmer Switch Ecodim

### ISSUE THREAD

**Issue by Vision100** [easyhomesrc/Homey_Issues#19]
Can you add support for Ecodim switch
![Simpel zigbee](https://user-images.githubusercontent.com/67784072/86493064-59467d00-bd70-11ea-837b-d415323893d6.JPG)

Device: Unknown Zigbee Device

IEEE: 0xccccccfffe25a236
Tyoe: Enddivice
Manufacturer: Ecodim
ProductID: ED-10013
ProfileID: 260

thnx

**Comment by easyhomesrc** [comment]
@Vision100 

I am very sorry, Homey requires that we can no longer add non-own brand products to the EasyHome App
