### ISSUE TITLE
Blitzwolf outlet BW-SHP13 (zigbee)

### ISSUE THREAD

**Issue by igiotis** [easyhomesrc/Homey_Issues#23]
Hi, could you possibly add the following outlet to read power consumption information ? Basic on-off works with homey but not the power info.

Man. ID. _TZ3000_3ooaz3ng
Product ID: TS0121
Device ID: 81
Profile ID: 260

Thanks a lot !

**Comment by easyhomesrc** [comment]
@igiotis 

I am very sorry, Homey requires that we can no longer add non-own brand products to the EasyHome App
