### ISSUE TITLE
Namron rotary dimmer (ZigBee)

### ISSUE THREAD

**Issue by christian-ruud** [easyhomesrc/Homey_Issues#5]
Hi -

The app doesn't seem to support the Namron ZigBee rotary dimmer, and I can't find any way to connect this to homey. There is support in the "Robb Smart" app, but that's for a different brand (different ids as I understand).

Any hope of adding support for this dimmer?

**Comment by maginawin** [comment]
@christian-ruud 

Can you connect the device to homey anyway? I need the `Advanced settings` page information in the `Device Page -> Edit Device`.
![F407A4AD-DF11-4B2C-A0BA-AC1556307273](https://user-images.githubusercontent.com/8154155/76683077-0f5c4e80-663c-11ea-87fc-086dbedff043.png)

**Comment by christian-ruud** [comment]
I haven't been able to add any device to homey as a generic zigbee device (including the other dimmers your app supports), only using the app devices. I have no idea why this doesn't work. What I've tried is to choose add device -> homey -> zigbee. Is there any special trick to making this work?

**Comment by christian-ruud** [comment]
I finally managed. No idea why, but I had to try maybe 10 timer before it worked...
![namron](https://user-images.githubusercontent.com/62177308/76685419-c7c1cc80-6613-11ea-9190-8550af65fe1e.jpg)

**Comment by maginawin** [comment]
@christian-ruud 

My suggestion for pairing:

Put the device closer to the Homey, 
Add ZigBee device in Homey App,
than quickly power off -> power on the device 5 times, the device has entered pairing mode now,

If still can’t pair, upgrade Homey gateway to latest firmware, restart the Homey gateway, then try again. 


I will update the App to support your device.

**Comment by christian-ruud** [comment]
Thank you! I was able to pair, and updated github with a screenshot.

Skaff deg Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by maginawin** [comment]
@christian-ruud EasyHome already supports your device

**Comment by christian-ruud** [comment]
Really? Attaching a picture of the device. I’ve tried both the things called “ZigBee Dimmer” in the app, but I haven’t been able to pair it..



Fra: Maginawin <notifications@github.com>
Sendt: mandag 23. mars 2020 07:14
Til: easyhomesrc/Homey_Issues <Homey_Issues@noreply.github.com>
Kopi: Christian Ruud <cru@develop.no>; Mention <mention@noreply.github.com>
Emne: Re: [easyhomesrc/Homey_Issues] Namron rotary dimmer (ZigBee) (#5)


@christian-ruud<https://github.com/christian-ruud> EasyHome already supports your device

**Comment by maginawin** [comment]
@christian-ruud 

Sorry about that, I updated a beta version, I don't have your device, please help me test it.

https://homey.app/en-us/app/com.easyhome.mw.zigbee/EasyHome/test/

**Comment by christian-ruud** [comment]
Now it worked when pairing with the second “Dimmer (ZigBee)”, and the device got added as “Light (DIM)”, and works as expected apart from appearing to be another device.

Fra: Maginawin <notifications@github.com>
Sendt: tirsdag 24. mars 2020 12:34
Til: easyhomesrc/Homey_Issues <Homey_Issues@noreply.github.com>
Kopi: Christian Ruud <cru@develop.no>; Mention <mention@noreply.github.com>
Emne: Re: [easyhomesrc/Homey_Issues] Namron rotary dimmer (ZigBee) (#5)


@christian-ruud<https://github.com/christian-ruud>

Sorry about that, I updated a beta version, I don't have your device, please help me test it.

https://homey.app/en-us/app/com.easyhome.mw.zigbee/EasyHome/test/

**Comment by maginawin** [comment]
@christian-ruud 

Please let me know if you have any questions about Homey - EasyHome App.

First, install Homey - EasyHome App, then you can directly add device by select Home - ZigBee, and Homey will automatically recognize them if the Apps installed by Homey support them.
