### ISSUE TITLE
Nordtronic zig-new dimmer

### ISSUE THREAD

**Issue by jjcph** [easyhomesrc/Homey_Issues#7]
Can you add this dimmer:

Nordtronic

![4317DF6D-E963-4574-BA1E-1611BA4D804B](https://user-images.githubusercontent.com/60128957/77473317-961be300-6e15-11ea-82f1-c4ddaf401b93.jpeg)

**Comment by easyhomesrc** [comment]
Hi, @jjcph 

Does Homey App EasyHome (v1.0.22) support **BoxDIM2 98425031** now?

**Comment by jjcph** [comment]
It does! Great work. Thanks.
